FROM python:3.5
MAINTAINER Baohua Yang <"baohyang@cn.ibm.com">
ENV TZ Asia/Shanghai

WORKDIR /app
COPY ./requirements.txt /app
RUN pip install --no-cache-dir  -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com -r requirements.txt

COPY . /app

RUN cd /tmp && wget -c https://nodejs.org/dist/v7.1.0/node-v7.1.0-linux-x64.tar.xz \
	&& tar -xvf node-v7.1.0-linux-x64.tar.xz && cp -r node-v7.1.0-linux-x64/* /usr/local/ \
	&& rm -rf node-v7.1.0-linux-x64*

# use this in development
CMD ["python", "dashboard.py"]

# use this in product
#CMD ["gunicorn", "-w", "128", "-b", "0.0.0.0:8080", "dashboard:app"]
