FROM python:3.5
MAINTAINER Baohua Yang <"baohyang@cn.ibm.com">
ENV TZ Asia/Shanghai

WORKDIR /app
COPY ./requirements.txt /app
RUN pip install  -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com -r requirements.txt

COPY . /app

ADD node-v6.2.0-linux-x64.tar.xz /usr/local/
run echo "registry = https://registry.npm.taobao.org" > /root/.npmrc

# use this in development
CMD ["python", "dashboard.py"]

# use this in product
#CMD ["gunicorn", "-w", "128", "-b", "0.0.0.0:8080", "dashboard:app"]
