FROM python:3.5
MAINTAINER Baohua Yang <"baohyang@cn.ibm.com">
ENV TZ Asia/Shanghai

WORKDIR /app
COPY ./requirements-watchdog.txt /app
RUN pip install  -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com -r requirements-watchdog.txt

COPY . /app

# use this in development
CMD ["python", "watchdog.py"]